name: BuildAndDeploy

on:
  push:
      
jobs:
  build-windows:
    runs-on: windows-latest
    env:
      QT_VERSION:     "5.15.2"
      MINGW_VERSION:  "win64_mingw81"
      MINGW_PATH:     "mingw81_64"
      BUILD_TYPE:     MinSizeRel
    
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        version: 8.1.0
        
    - name: Install Qt
      uses: jurplel/install-qt-action@v3.0.0
      with:
        host: windows
        version: ${{ env.QT_VERSION }}
        arch: ${{ env.MINGW_VERSION }}
        dir: "${{github.workspace}}/qt"
        cache: true
        
    - name: Set Qt path and refresh the environment
      run: |
        echo "${{github.workspace}}/qt/Qt/${{ env.QT_VERSION }}/${{ env.MINGW_PATH }}/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        refreshenv
        
    - name: Configure the CMake project
      env:
        CMAKE_PREFIX_PATH: ${{env.Qt5_Dir}}
      run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "CodeBlocks - MinGW Makefiles" -B ${{github.workspace}}/build

    - name: Build the project
      run: cmake --build ./build
      
    - name: Deploy the program
      run: |
        mkdir build/all
        cp build/MissileGuidanceExercise build/all
        cd build/all
        windeployqt MissileGuidanceExercise --release
        ls
        Compress-Archive -Path build/all -DestinationPath build/artifacts.zip
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Windows-targeted executable package
        path: build/artifacts.zip
      
